[package]
name = "mwtest"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]
edition = "2018"
default-run = "mwtest"

[dependencies]
structopt = "*"
regex = "1.3.*"
uuid = { version = "0.8.*", features = ["v4"] }
term_size = "0.3.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
serde = "1.0.*"
glob = "0.3.*"
num_cpus = "1.11.*"
htmlescape = ">= 0.3.*"
futures = "0.3.*"

[dependencies.tokio]
version = "0.2.*"
features = ["net", "process", "io-util", "time"]

[lib]
name = "xge_lib"
path = "lib/xge_lib.rs"

#[profile.release]
#lto = true
#opt-level = 'z'
#codegen-units = 1
#panic = 'abort'