[package]
name = "mwtest"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]

[dependencies]
clap = "2.32.0"
regex = "1.0.6"
uuid = { version = "0.7.1", features = ["v4"] }
#termion = "1.5.1"
handlebars = "1.1.0"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde = "1.0.80"
glob = "0.2"