[package]
name = "mwtest"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]
edition = "2018"

[dependencies]
clap = ">= 2.32.0"
regex = ">= 1.1.0"
uuid = { version = ">= 0.7.1", features = ["v4"] }
term_size = ">= 0.3.1"
serde_json = ">= 1.0.34"
serde_derive = ">= 1.0.84"
serde = ">= 1.0.84"
glob = ">= 0.2"
num_cpus = ">= 1.9.0"
htmlescape = ">= 0.3.1"
tokio = ">= 0.2.0-alpha.1"
tokio-process = ">= 0.3.0-alpha.1"
futures-preview = ">= 0.3.0-alpha.17"

[lib]
name = "xge_lib"
path = "lib/xge_lib.rs"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'