[package]
name = "mwtest"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]
edition = "2018"

[dependencies]
clap = ">= 2.32.0"
regex = ">= 1.1.0"
uuid = { version = ">= 0.7.1", features = ["v4"] }
term_size = ">= 0.3.1"
handlebars = ">= 1.1.0"
serde_json = ">= 1.0.34"
serde_derive = ">= 1.0.84"
serde = ">= 1.0.84"
glob = ">= 0.2"
scoped_threadpool = ">= 0.1.9"
num_cpus = ">= 1.9.0"
htmlescape = ">= 0.3.1"

[lib]
name = "xge_lib"
path = "lib/xge_lib.rs"

[profile.release]
lto = true
panic = 'abort'