[package]
name = "mwtest"
version = "0.1.0"
authors = ["Fabian Beckmann <fb@phaseq.de>"]

[dependencies]
clap = "2.32.0"
regex = "1.0.6"
uuid = { version = "0.7.1", features = ["v4"] }
indicatif = "0.9.0"